import type { Metadata } from "next"
import type React from "react" // Added import for React
import "./globals.css"
import { MainNav } from "./_components/navbar/NavbarMain"
import { Toaster } from "@/components/ui/toaster"
import { getAnnouncement } from "@/lib/actions/announcement.actions"
import { AnnouncementBar } from "./_components/navbar/AnouncementBar"
import { getUserSession } from "@/lib/actions/auth.actions"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { data: announcement, message } = await getAnnouncement()
  const { data: user, message: userMessage } = await getUserSession()

  return (
    <html lang="en">
    <body className="antialiased">
      {/* Fixed Navbar */}
      <div className="fixed top-0 left-0 w-full z-50 bg-brand-light shadow-md">
        <AnnouncementBar content={announcement?.content} />
        <MainNav user={user} />
      </div>

      {/* Main Content - Add Padding to Prevent Overlapping */}
      <main className="flex-grow pt-[6.5rem]">{children}</main>

      <Toaster />
    </body>
  </html>
  )
}

