import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/lib/auth/SessionProvider";
import Header from "@/components/app/header/Header";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/app/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <Header />
          <main className="bg-primary text-black pb-10 pt-14 flex flex-col">
            {children}
          </main>
          <Footer />
        </body>
        <Toaster />
      </NextAuthProvider>
    </html>
  );
}

